services:
  app:
    container_name: weatherApiContainer
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_PORT=6379
      - API_KEY=${API_KEY}
    depends_on:
      - cache


  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data[


volumes:
  redis_data: